version: "3.3"

services:
    dronedb:
        image: mariadb:11
        volumes:
            - data-mysql:/var/lib/mysql
            - ./initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=password
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
            timeout: 20s
            retries: 10
    registry:
        depends_on:
            - dronedb
        image: dronedb/registry
        tmpfs:
            - /tmp
        volumes:
            - ./data:/data
            - ./appsettings-testing.json:/data/appsettings.json
        ports:
            - "5000:5000"
        restart: unless-stopped

volumes:
  data-mysql:
    driver: local
